version: "3"
services:
  db:
    image: postgres:11.1-alpine
    container_name: hastecloud_postgresql
    environment:
      POSTGRES_DB: hastecloud
      POSTGRES_USER: hastecloud
      POSTGRES_PASSWORD: hastecloud
    ports:
      - 5432:5432
    volumes:
      - "hastecloud_db:/var/lib/postgresql/data"

  hastecloud:
    image: hastecloud-app
    container_name: hastecloud
    ports:
      - 9090:9090
    depends_on:
      - db
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://hastecloud:5432/hastecloud"
      - "SPRING_DATASOURCE_USERNAME=hastecloud"
      - "SPRING_DATASOURCE_PASSWORD=hastecloud"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
