spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hastecloud
    username: hastecloud
    password: hastecloud
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always